sudo: required
services:
  - docker

before_install:
  - docker build -t nveshledat/docker-react -f Dockerfile.dev .

script:
      - docker run -e CI=true nveshledat/docker-react npm run test
## -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-835359887603"
  bucket_path: "docker"
  on:
    branch: master
  #access_key_id: $AWS_ACCESS_KEY
  access_key_id: "AKIA4E72UKDZWWGVM7XS"
  #secret_access_key: $AWS_SECRET_KEY
  #  secure: "$AWS_SECRET_KEY"
  secret_access_key: "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"

#http://dockerreact-env-1.eba-vynmuftp.us-east-2.elasticbeanstalk.com/
#Docker-env.eba-jva2jimx.us-east-2.elasticbeanstalk.com
#elasticbeanstalk-us-east-2-835359887603
